
version: 2.1
orbs:
  discord: teka23/discord@0.0.1
jobs:
  build-and-test: 
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Weather app
          command: docker build . -t weather      
      - run:
          name: Run tests
          command: docker run --rm -d weather python3 -m unittest WeatherAppTest.py
      - discord/status:
          fail_only: true
          webhook: https://discord.com/api/webhooks/1041448092475588710/WTNhSyF_4-6T1FdlU1EKKkEi0Ops6OdROkv5zCSpKpsANBe3m3uAUgkW14gonjj_OSjI 
          failure_message: "You Suck"
      - discord/status:
          success_only: true
          webhook: https://discord.com/api/webhooks/1041448092475588710/WTNhSyF_4-6T1FdlU1EKKkEi0Ops6OdROkv5zCSpKpsANBe3m3uAUgkW14gonjj_OSjI
          success_message: "You Rock"    
  push-to-gitlab-registry:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and tag Docker image
          command: |
              docker build . -t registry.gitlab.com/devops2695516/circleciproj/weatherapp:<< pipeline.number >>
              docker tag registry.gitlab.com/devops2695516/circleciproj/weatherapp:<< pipeline.number >> registry.gitlab.com/devops2695516/circleciproj/weatherapp:latest
      - run:
          name: Push Docker image to GitLab registry
          command: |
              echo "$GITLAB_REGISTRY_PASSWORD" | docker login --password-stdin -u "$GITLAB_REGISTRY_USER"  registry.gitlab.com
              docker push registry.gitlab.com/devops2695516/circleciproj/weatherapp:<< pipeline.number >>
              docker push registry.gitlab.com/devops2695516/circleciproj/weatherapp:latest
  test-terraform-code:
    docker:
      - image: python:3.10-slim
    steps:
      - checkout
      - run:
          name: test with checkovv
          command: |
            pip3 install checkov
            ls
            checkov -d /TerraF          
  # update-image-version-in-deployment:
  #   docker:
  #     - image: cimg/base:2021.04
  #   steps:
  #     - checkout:
workflows:
  sample: 
    jobs:
      - build-and-test:
          filters:
             branches:
              only:
                 main
      - push-to-gitlab-registry:
          requires:
            - build-and-test
          filters:
             branches:
              only:
                 main  
      - test-terraform-code:
          requires:
            - push-to-gitlab-registry
          filters:
             branches:
              only:
                 main  
